/*
  # Fix reminders table ID column for auto-increment

  1. Database Changes
    - Convert the reminders table ID column to use GENERATED BY DEFAULT AS IDENTITY
    - This ensures new reminders get automatic IDs when inserted

  2. Security
    - Maintain existing RLS policies
*/

-- Convert the reminders table ID column to auto-increment
-- First, we need to check if the column already has IDENTITY, if not, add it
DO $$
BEGIN
  -- Check if the id column already has IDENTITY
  IF NOT EXISTS (
    SELECT 1 
    FROM information_schema.columns 
    WHERE table_name = 'reminders' 
    AND column_name = 'id' 
    AND is_identity = 'YES'
  ) THEN
    -- Add IDENTITY to the existing id column
    ALTER TABLE reminders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  END IF;
END $$;